# Generated by Django 3.2.8 on 2021-12-24 09:18

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'required': 'Xin lỗi, đây không phải là số điện thoại'}, max_length=50, region=None, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Số điện thoại liên hệ', max_length=128, region=None),
        ),
    ]
