# Generated by Django 3.2.8 on 2021-12-18 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_display'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Display',
        ),
    ]
