# Generated by Django 3.2.8 on 2021-12-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Problem',
            field=models.TextField(blank=True),
        ),
    ]
