# Generated by Django 3.2.8 on 2021-12-13 03:56

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_key',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=20),
        ),
    ]
