# Generated by Django 3.2.8 on 2021-12-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_order_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isRate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
