# Generated by Django 3.2.8 on 2021-12-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20211218_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rating',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
