# Generated by Django 3.2.8 on 2021-12-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_save_item_list_save_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save_list',
            name='title',
            field=models.CharField(blank=True, default='None', max_length=50),
        ),
    ]
