# Generated by Django 3.2.8 on 2021-12-25 05:31

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_producttype_slug'),
        ('orders', '0014_alter_save_list_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Direct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(error_messages={'required': 'Xin lỗi, đây không phải là số điện thoại'}, max_length=50, region=None, verbose_name='Số điện thoại')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total_paid', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Order_Item_Direct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_direct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_direct', to='orders.order_direct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_direct_item', to='store.product')),
            ],
            options={
                'ordering': ('order_direct',),
            },
        ),
    ]
