# Generated by Django 3.2.8 on 2021-12-25 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_direct_order_item_direct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item_direct',
            name='order_direct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_direct_id', to='orders.order_direct'),
        ),
    ]
